/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface ProblemDetails {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
}

export interface RegistrationSummary {
    registrationId?: number | string;
    registrationNumber: string;
    expiryDateUtc?: Date;
    vehicleId?: number | string;
    userId: string;
    isExpired?: boolean;
}

export interface VehicleSummary {
    userId: string;
    vehicleId?: number | string;
    registrationId?: number | string;
    make: string;
    model: string;
    year?: number | string;
    currentRegistrationNumber?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
