/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { MakeService } from "./make.service";
export { RegistrationService } from "./registration.service";
export { VehicleService } from "./vehicle.service";
export { WebApplication1Service } from "./webApplication1.service";
