/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Vehicle controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, VehicleSummary } from "../models";

@Injectable({ providedIn: "root" })
export class VehicleService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiVehiclesGet(make?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<VehicleSummary>>;
    apiVehiclesGet(make?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<VehicleSummary>>>;
    apiVehiclesGet(make?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<VehicleSummary>>>;
    apiVehiclesGet(make?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/vehicles`;

        let params = new HttpParams();
        if (make != null) {
            params = HttpParamsBuilder.addToHttpParams(params, make, 'make');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiVehiclesIdGet(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<VehicleSummary>;
    apiVehiclesIdGet(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<VehicleSummary>>;
    apiVehiclesIdGet(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<VehicleSummary>>;
    apiVehiclesIdGet(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/vehicles/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
